version: "3.8"

services:
  ros2-dev:
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
        USERNAME: val
    image: ros2-humble-val
    container_name: ros2_dev_env
    privileged: true
    network_mode: host
    group_add:
      - "985" #getent group uucp | cut -d: -f3
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /dev:/dev
      - /home/${USER}/DeepSight-Nebula/:/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    command: bash
