# Default initial positions for hiwonder_esp32's ros2_control fake system

# Default pose uses positions inside the measured safe joint limits.
initial_positions:
  gripper_left_joint: 0.0
  limb1_to_base_link_joint: 0.048592
  limb2_to_limb1_joint: 1.148692
  limb3_to_limb2_joint: 1.140315
  limb4_to_limb3_joint: -1.759371
  limb5_to_limb4_joint: -0.008483
